// Generated by multisetgen. DO NOT EDIT!
package main

import "fmt"

type MultiSet map[string]int

func NewMultiSet() MultiSet {
	return MultiSet{}
}

func (m MultiSet) Insert(val string) {
	m[val]++
}

func (m MultiSet) Erase(val string) {
	if _, exists := m[val]; !exists {
		return
	}
	m[val]--
	if m[val] <= 0 {
		delete(m, val)
	}
}

func (m MultiSet) Count(val string) int {
	return m[val]
}

func (m MultiSet) String() string {
	vals := ""
	for val, count := range m {
		for i := 0; i < count; i++ {
			vals += fmt.Sprint(val) + " "
		}
	}
	return "{ " + vals + "}"
}
